# Use an official Golang runtime as a parent image
FROM golang:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Build the Go application
RUN go build -o main

# Expose port 3001
EXPOSE 3001

# Command to run the executable
CMD ["./main"]
